# Generated by Django 5.1.6 on 2025-02-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(default='Sedan', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='customs_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='cylinders',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='drivetrain',
            field=models.CharField(default='FWD', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='emission_class',
            field=models.CharField(default='Euro 6', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.DecimalField(decimal_places=1, default=1.6, max_digits=4),
        ),
        migrations.AddField(
            model_name='car',
            name='first_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='full_service_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.CharField(default='Manual', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='gears',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='general_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='weight',
            field=models.IntegerField(default=1200),
        ),
    ]
