# Generated by Django 5.1.6 on 2025-03-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='options',
        ),
        migrations.AddField(
            model_name='car',
            name='options',
            field=models.ManyToManyField(blank=True, to='api.option'),
        ),
    ]
