# Generated by Django 5.1.6 on 2025-03-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_option_remove_car_options_car_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='category',
            field=models.CharField(choices=[('COMFORT', 'Comfort & Convenience'), ('ENTERTAINMENT', 'Entertainment & Media'), ('SAFETY', 'Safety & Security'), ('EXTRAS', 'Extras')], default='EXTRAS', max_length=20),
        ),
    ]
