# Generated by Django 5.1.6 on 2025-08-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_slug_field'),
    ]

    operations = [
    ]
