# Generated by Django 5.1.6 on 2025-03-07 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_optioncategory_option_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExteriorColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hex_code', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.AddField(
            model_name='car',
            name='exterior_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.exteriorcolor'),
        ),
        migrations.CreateModel(
            name='InteriorColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upholstery', models.CharField(max_length=100)),
                ('hex_code', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'unique_together': {('name', 'upholstery')},
            },
        ),
        migrations.AddField(
            model_name='car',
            name='interior_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.interiorcolor'),
        ),
    ]
