# Generated by Django 5.1.6 on 2025-03-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exteriorcolor_remove_car_color_car_exterior_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='discussed_price',
            field=models.BooleanField(default=False),
        ),
    ]
