# Generated by Django 5.1.6 on 2025-03-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.AddField(
            model_name='car',
            name='first_registration_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='first_registration_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='first_registration_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
