# Generated by Django 5.1.6 on 2025-03-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_car_year_car_first_registration_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='general_inspection_date',
        ),
    ]
